export const locators = {
    agentPortal : `//button[normalize-space()='Agent Portal']`,
    userNameLoc : `//input[@id='username']`,
    passwordLoc : `//input[@id='password']`,
    submitButton : `//button[@type='submit']`,
    bridgerLogo : `//img[@alt='App-bar-logo']`,
    newSubmissionBtn : `//button[normalize-space()='New Submission']`,
    stateDropdown :`//button[normalize-space()='New Submission']`,
    selectState : `#pol_issued_state`,
    programDrodown : `//select[@id='pol_lob']`,
    selectProgram : `#pol_lob`,
    selectTerm : `#pol_term`,
    fName : `[data-test="f_firstName"]`,
    lName : `[data-test="f_lastName"]`,
    continueBtn : `[data-test="dialogActions-continue-btn"]`,
    cellPhone : `//input[@id='pol_insured_cell_phone']`,
    emailid : `//input[@id='pol_insured_email']`,
    nextBtn : `//button[@type='submit']`,
    streetAddress : `//input[@id=':r4o:']`,
    selectaddress : '//li[1]/div/p',
    addVehicleBtn : `[data-test="add-vehicle-button"]`,
    vehicleYear : `[data-test="f_vehicle_year"]`,
    selectYear : (year) => `//li[text()='${year}']`,
    vehicleVin : `[data-test="f_vehicle_vin"]`,
    searchVinBtn : `[data-test="search-by-vin-btn"]`,
    disabledSearchVinBtn : `//button[@disabled]`,
    filledMakeTextBox : `//label[@id='vehicle_make-label' and @data-shrink='true']`,
    vehicleCost : `//input[@id='vehicle_msrp']`,
    vehicleUse : `[data-test="f_vehicle_use"]`,
    purchasedDate : `//input[@id='vehicle_purchased']`,
    purchasedStatus : `[data-test="f_vehicle_is_new"]`,
    damageStatus : `[data-test="f_vehicle_damage"]`,
    saveButton : `//button[normalize-space()='Save']`,
    addedVehicle: (vin) => `//span[text()='${vin}']`,
    nextButton : `[data-test="next-btn"]`,
    insuredRated : `//span[contains(text(),'Insured,')]`,
    updateDriver : `//span[normalize-space()='Update']`,
    driverGender : `#driver_gender`,
    driverMaritalStatus : `[data-test="f_driver_marital_status"]`,
    driverDOB : `[data-test="f_driver_dob"]`,
    driverLicenseStatus : `[data-test="f_driver_license_status"]`,
    driverLicenseYears : `//input[@id='driver_license_years']`,
    driverLicenseMonths : `//input[@id='driver_license_month']`,
    licenseTxtBox : `//input[@id='driver_license_number']`,
    driverOccupation : `[data-test="f_driver_occupation"]`,
    selectAccountant : `//ul[@id='driver_occupation-listbox']/li[text()='Accountant']`,
    driverSubmitBtn : `[data-test="driver-drawer-submit"]`,
    policyEffectiveDate : `//h5[normalize-space()='Policy Effective Date']`,
    coveragePage : `//h5[normalize-space()='Coverages']`,
    pipSwitch : `[data-test="coverage-item-switch-Personal Injury Protection (PIP)"]`,
    refreshPriceBtn : ` //button[normalize-space()='Refresh Price']`,
    premiumValue : `[data-test='premium-summary-price-0']`,
    paymentOptions : `//h5[normalize-space()='Payment Options']`,
    proceedQuoteBtn : `//button[@type='button'][normalize-space()='Proceed to Quote']`,
    disabledProceedBtn : `//button[@data-test='refresh-price-btn']/following-sibling::span/button[@disabled]`,
    validateEligibilityBtn : `//button[@type='submit']`,
    uwQueryPage : `//h5[normalize-space()='Underwriting/Eligibility Questions']`,
    Question_1 :`//div[div[span[contains(text(),'Are all household members')]]]/div[2]//span[2][text()='Yes']`,
    Question_2 : `//div[div[span[contains(text(),'Is the spouse of any')]]]/div[2]//span[2][text()='Yes']`,
    Question_3 : `//div[div[span[contains(text(),'Does any operator have')]]]/div[2]//span[2][text()='No']`,
    Question_4 : `//div[div[span[contains(text(),'Any drivers self-employed')]]]/div[2]//span[2][text()='No']`,
    Question_5 : `//div[div[span[contains(text(),'Has any driver been convicted')]]]/div[2]//span[2][text()='No']`,
    Question_6 : `//div[div[span[contains(text(),'Will any vehicle be used')]]]/div[2]//span[2][text()='No']`,
    Question_7 : `//div[div[span[contains(text(),'Are any automobiles')]]]/div[2]//span[2][text()='No']`,
    Question_8 : `//div[div[span[contains(text(),'Have any automobiles')]]]/div[2]//span[2][text()='No']`,
    Question_9 : `//div[div[span[contains(text(),'Are any of the automobiles')]]]/div[2]//span[2][text()='No']`,
    paymentSigningDetails : `//h5[normalize-space()='Payment and Signing Details']`,
    checkNumberTextBox : `//input[@id='pol_payment_check_number']`,
    confirmPage : `//h4[normalize-space()='Confirm and Sign to Complete Purchase']`,
    agentCheckBox : `//div[h5[contains(text(), "Agent's Signature")]]//span[contains(text(),'the')]`,
    applicantCheckBox : `//div[h5[contains(text(), "Applicant's Signature")]]//span[contains(text(),'the')]`,
    agentSignature : `//input[@placeholder='KK Pattnaik']`,
    applicantSignature : `//div[h5[contains(text(), concat('Applicant', "'", 's Signature'))]]//div[div/span[text()='Full Legal Name*']]//input`,
    termAndConditions : `//h5[normalize-space()='Terms and Conditions']`,
    disabledagreeButton : `//button[@data-testid='agree-button'][@disabled]`,
    agreeButton : `//button[text()='Agree']`,
    officeEsign : `//div[text()='In Office eSign']`,
    agentSignaturePlaceholder : `//div[h5[contains(text(), "Agent's Signature")]]//input[@placeholder]`,
    applicantSignaturePlaceholder : `//div[h5[contains(text(), "Applicant's Signature")]]//input[@placeholder]`,
    modal : `//div[@class='MuiBox-root mui-wvmse7']`,
    AuthText : `//h6[text()='Authentication']`,
    purchaseButton : `//button[text()='Proceed with Purchase']`,
    successPolicyMsg : `//h5[contains(text(),'successfully purchased the policy.')]`,
    policyNumber : `//div[span[text()='Policy Number']]/following-sibling::div/span`,
    insuredName : `//div[span[text()='Named Insured']]/following-sibling::div/span`,
    policyTerm :   `//div[span[text()='Policy Term']]/following-sibling::div/span`,
    paymentPlan : `//div[span[text()='Payment Plan']]/following-sibling::div/span`,
    totalPremium : `//div[span[text()='Premium Total']]/following-sibling::div/span`,
    policyPageBtn : `//button[@data-test='go-to-policy-page-btn']`,
    coverageSummaryBtn : `//button[@data-test='tab_coverage_summary']`,
    BiLimit : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[2]/td[2]`,
    BiPremium : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[2]/td[4]`,
    PdLimit : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[3]/td[2]`,
    PdPremium : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[3]/td[4]`,
    PipLimit : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[4]/td[2]`,
    PipPremium : `//div[h5[text()='Coverage Summary']]/following-sibling::div[1]//tr[4]/td[4]`,
    fraudFee : `//td[@data-test='tax-fee-Fraud Fee']`,
    policyFee : `//td[@data-test='tax-fee-Policy Fee']`
};
